### ISSUE TITLE
Pools are hidden in Daedalus randomly

### ISSUE THREAD

**Issue by bigpey** [input-output-hk/daedalus#2117]
I built a stakepool and it showed up in Daedalus for me right away, when my followers went to find it and delegate many of them did. But a big portion, I would say around 30% state that they can not see the pool at tall in Daedalus. The meta-data is correct and I have delegated to my pool and so have many others. This is not just a problem for my pool it is a problem for other pools as well. It seems to be random but Daedalus is not showing all of the pools.

**Comment by Willburn** [comment]
In my case the 3 computers having installed daedelus very early did not show my 2nd pool ANPNL and other users reported the same and I sadly had to take the step to retire the pool and make it again. But laptop that installe deadelus wallet today showed it without problems both the new and the one that is retiring epoch 209. Could this have something to do with stored ledger information in daedelus?

**Comment by bigpey** [comment]
I also must say that my stakepool partner can not see the pool either in his Daedalus, where as I am delegated to it. He sees many other pools but not near as many as ADApools or pooltool lists.

**Comment by CrazyHolland** [comment]
DUCK showed up right away after registering.
After reregistering I was notified within minutes DUCK disapeared out of the Daedalus ticker page.
Some see my ticker in their wallet, some dont.

**Comment by bigpey** [comment]
> DUCK showed up right away after registering.
> After reregistering I was notified within minutes DUCK disapeared out of the Daedalus ticker page.
> Some see my ticker in their wallet, some dont.

This seems to be what happened to me too. Last night I got the stakepool up around 1am EST and then following that everyone in my discord server that was waiting for the pool delegated fine. Not one single person stated that they couldn't see the pool, they all delegated. Fast forward to this morning I create the video and post it, a high precentage of people can't see the pool in the morning after the video was posted. The people that saw the pool at night still can see the pool. I can still see my pool, some people starting it can still see it. 

Hope that information helps.

**Comment by oneworldcardanostaking** [comment]
I'm experiencing similar with ONEW, after making changes to the metadata yesterday to include the extended option my pool has disappeared from daedalus. I've checked the ledger and it looks right along with pooltool and adapool sources however it does not appear in cardano-wallet as well. I have now been told it shows up randomly for certain people but not others.

Cheers, Jason

**Comment by zorrbass** [comment]
Same for ATLAS. It shows up fine on my PC. But on the laptop it does not. Also the laptop wallet the total number of pools is lower by three.

**Comment by bigpey** [comment]
The pool is now appearing for a lot of those people.

**Comment by bigpey** [comment]
I wanted to give some more information on this. For many the pool has start appearing. But for some there is still an issue when they first download the wallet that it can take 12+ hours to load all of the pools. It's not just my pool it's many and they seem to come around the same time for people.

**Comment by leaf-pool** [comment]
Something similar for LEAF. If the pool is re-registered with extended metadata it disappears from Daedalus. In pooltool the green ticker is shown and the information about the metadata file (url+hash) are correct but the ticker is not showing in Deadalus. As soon as the pool is re-registered with the previous metadata file it reappears in Daedalus.

**Comment by PierreManos** [comment]
Same issue here. I registered 5 hours ago and GREEN appears nowhere... I hope this issue is addressed by the IOHK wizards and I am sure they are aware of it by now.

**Comment by darrenjschumaker** [comment]
Same issue happening for CHAMP ticker.  Registered pool via cntools and it is showing as verified via pooltool, but has not shown up in Daedalus.  I've attempted modifying the registration (slight change to stake, margin, etc) to see if it helps, without success.

**Comment by prometheus-pool** [comment]
Just wanted to say I've also been experience this issue. Myself and 2 others all see different total numbers of stake pools and some of us don't see certain pools that the others do, this is after multiple restarts of the wallet and over 24 hours of time so it seems there is something deeper going on than just being in sync.

**Comment by skadea** [comment]
I have a similar problem. I registered my new pool and successfully query the pool id from the blockchain. But my pool is not listed. Seems that there are only about 433 pools listed, though on adapools.com you can see more than 500 pools.
Pool name: SKADEA
Ticker: skad

**Comment by oneworldcardanostaking** [comment]
It seems Daedalus is caching the meta hash so if Daedalus is opened when meta is changed it checks the new meta based on the existing hash and will find it to be a mismatch and remove the pool. The pool should show up again once it updates to the correct hash.

**Comment by haskellcoding29** [comment]
My pool is also disappeared after re-registering with changing the extended-metadata.json.
pool name : JOY
Ticker: JOY

**Comment by tobg** [comment]
Same issue here. After changed some pool attributes and re-register, pool is not visible in daedalus anymore. pooltool.io shows that everything is ok.

**Comment by TurboEgon** [comment]
Also here for NOVA.
Seems like changing the metadata trifgers this issue.
Also sometimes it is visible on one daedalus mashine but not visible on another, so thats a daedalus issue

**Comment by msuleman** [comment]
Same here for CHAIN and UPS.
Registered fine initially around 02:00 UTC on Thurs 30th - appeared in seconds/minutes on Daedalus.
Amended fee and description around 14:00 yesterday, not seen either pool in Daedalus since - pooltool showed updated info/correct hash by its next check - within an hr of update approx.

**Comment by snmoney** [comment]
same here : ADA4G

**Comment by avilsmeier** [comment]
One more over here. TOPO1

**Comment by DarkPaladin56** [comment]
Having the same issue: BEAVR

**Comment by Griff1221** [comment]
RADAR and BADAS are in the same boat. Not being in Daedalus initially and k = 150 it feels like "Game over man!"

**Comment by adaclimb** [comment]
same issue. CLIMB isn't showing up

**Comment by namanChaturvedi** [comment]
just like others.....[BUBBA] pool doesn't show up. What's the point being setup before 1 epoch, and face disappointment with wallet backend. 3 party tools have been doing better in showing up the pool, right away. But Daedalus back end sucking it all up at launch.

**Comment by Bluecollar-crypto** [comment]
BLCLR is not showing up on Daedalus. 
Showing on PT and ADApools. Please fix this!!!

**Comment by tayrosa** [comment]
same issue. ISP isn't showing up. Please fix!

**Comment by vmartinez-sparta** [comment]
Same Issue for SPRTA. I have been waiting over a day and nothing. Pooltool and Adapools is fine. Please fix this. Thank you

**Comment by wtrask4** [comment]
SAGE was visible, was gaining delegation, then I modified the poolmeta.json to include the newly created website and copied the new meta file directly from my node to my server (same as first registration).

After that I was delisted from Daedalus.  Adapools shows SAGE is correctly listed.

Now funds that were delegated to SAGE are displayed as Undelegated -> Unknown


My main question is requesting a formal response from IOHK about if we should retire these pools vs a Daedalus patch is released before the end of Epoch 208.

Thanks!

<img width="333" alt="A2200CFC-0953-437B-B578-86167B21866E" src="https://user-images.githubusercontent.com/19297128/89126797-f72f8380-d4a5-11ea-9186-a17225398d8e.png">
![5EF0E340-2B23-44BA-9F83-DD9D7B1183FC](https://user-images.githubusercontent.com/19297128/89126799-f860b080-d4a5-11ea-9e60-93b758af333e.jpeg)

**Comment by wtrask4** [comment]
![214F3419-7AFF-4AE7-94C9-721C4A44C759](https://user-images.githubusercontent.com/19297128/89126894-c4d25600-d4a6-11ea-8640-0eb4223b780d.jpeg)

**Comment by cyber-russ** [comment]
Same issue ADV. Good on pooltools.
Cheers

**Comment by chadle-git** [comment]
We are having the same issue. Shows up fine in adapools.org and pooltool.io

**Comment by TurboEgon** [comment]
Guys, please dont left us behind, as the next epoch is approaching and we are not getting new and losing old stakeholders.
An official statement would be very helpful.
There is also a reddit thread, if that helps
https://www.reddit.com/r/cardano/comments/i276us/charles_daedalus_is_not_as_promising_as_nodes/

**Comment by KtorZ** [comment]
In order to help figuring out the problem, may any stake pool operator having issue here answer the two following questions:

#### Are you using a 3rd party service / URL shortener to serve your metadata file? 

#### Did you make several registrations? If yes, did they use the same URL and/or the same metadata Hash? 

Thank you :pray:

**Comment by CrazyHolland** [comment]
Daedalus is not updating metadata.

200 pools not showing up in Daedalus incl. IOG1 -IOG20.

Running metadata of github.
Worked fine untill reregistration.
Most wallets show DUCK, still some dont.
Reregistering the pool with updated metadata makes the pool fall out of some Daedalus wallet, but not all.
ADApools en Pooltool.io show data is ok.
Only Daedalus doesnt update the hash in all wallets

Thank you too


-------- Oorspronkelijk bericht --------
Van: Matthias Benkort <notifications@github.com>
Datum: 03-08-20 09:33 (GMT+01:00)
Aan: input-output-hk/daedalus <daedalus@noreply.github.com>
Cc: CrazyHolland <alexdegeus@hotmail.com>, Comment <comment@noreply.github.com>
Onderwerp: Re: [input-output-hk/daedalus] Pools are hidden in Daedalus randomly (#2117)


In order to help figuring out the problem, may any stake pool operator having issue here answer the two following questions:

Are you using a 3rd party service / URL shortener to serve your metadata file?
Did you make several registrations? If yes, did they use the same URL and/or the same metadata Hash?

Thank you 🙏

**Comment by avilsmeier** [comment]
Hi. I tried several options, and I did change my metadata, the pledge and the margin a couple times.
Hosted the file in 3 different links.

My site
Gist
And now in Google cloud storage. No shortener.

About 2 hours ago I registered a second pool TOPO2 with everything done according to the instructions in github. Haven't changed the metadata and registered a single time with the file hosted directly in Google but I'm not seeing this one either in Daedalus. Adapools and pooltool show my info correctly for both pools. If you need anything else lemme know. Thank you!


Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by nikolaglumac** [comment]
Daedalus is displaying ALL the stake pools it gets from cardano-wallet Api. Please make sure your Daedalus instance is fully synced and your stake pool is correctly set up: https://github.com/input-output-hk/daedalus/issues/2117#issuecomment-667859148

**Comment by CrazyHolland** [comment]
Daedalus did show 435 pools max. But if its fixed now, its fixed. (Cant check now)


-------- Oorspronkelijk bericht --------
Van: Nikola Glumac <notifications@github.com>
Datum: 03-08-20 10:01 (GMT+01:00)
Aan: input-output-hk/daedalus <daedalus@noreply.github.com>
Cc: CrazyHolland <alexdegeus@hotmail.com>, Comment <comment@noreply.github.com>
Onderwerp: Re: [input-output-hk/daedalus] Pools are hidden in Daedalus randomly (#2117)


Daedalus is displaying ALL the stake pools it gets from cardano-wallet Api. Please make sure your Daedalus instance is fully synced and your stake pool is correctly set up: #2117 (comment)<https://github.com/input-output-hk/daedalus/issues/2117#issuecomment-667859148>

**Comment by PierreManos** [comment]
Salut Matthias,
1) Yes, I used git.io to shorten the URL of the Github repo. raw version of my Metadata json file.
2) Yes two registrations: 1st one was accepted. When I ran the `cardano-cli shelley stake-pool metadata-hash` command that checks our file fits the required schema, it got accepter, got a hash and I got a Pool ID. Appeared nowhere.
>A day later I realised my Json had an error (missing apostrophe), so had to resubmit and do another registration. It was the same Metadata hash, and the same pool ID. No Daedalus, but appeared on pooltool/adapools instantly.

**Comment by adosiawolf** [comment]
@KtorZ - I registered 4 pools for clients on 8/1

all metadata links are direct links to hosted file, and all pools were only registered once

my personal pools display in Daedalus fin (registered within hours following the hard fork), whereas none of the 4 pools registered on 8/1 appear in Daedalus - meta file hashes were all derived via exact copy of meta host file pulled via wget and double checked

**Comment by cyber-russ** [comment]
> In order to help figuring out the problem, may any stake pool operator having issue here answer the two following questions:
> 
> #### Are you using a 3rd party service / URL shortener to serve your metadata file?
> #### Did you make several registrations? If yes, did they use the same URL and/or the same metadata Hash?
> Thank you 🙏

Pool- ADV
No to 3rd party service/ URL shortener. 
Yes to multiple registrations, (but only because the first one didn't work after 24 hours). The metadata hash would have changed as the pool description was made slightly simpler. URL would have changed as I tried different names for poolmeta file to try and troubleshoot.

**Comment by MrMaik** [comment]
> In order to help figuring out the problem, may any stake pool operator having issue here answer the two following questions:
> #### Are you using a 3rd party service / URL shortener to serve your metadata file?
no
> #### Did you make several registrations? If yes, did they use the same URL and/or the same metadata Hash?
yes and yes (same url)

**Comment by msuleman** [comment]
Are you using a 3rd party service / URL shortener to serve your metadata file?
No
Did you make several registrations? If yes, did they use the same URL and/or the same metadata Hash?
First 2-3 - same/URL & different metadata Hash
Last -one for CHAIN - re-used same URL/metadata as for 1st (working) registration - has not resulted in appearance in 
daedalus
Last one for UPS - used unique URL based on reg date/time and new metadata hash - has not resulted in appearance in daedalus

**Comment by tobg** [comment]
Are you using a 3rd party service / URL shortener to serve your metadata file?
First version which was visible in Daedalus used my own github url. 2nd version which is not visible anymore is using url from pooltool.io

Did you make several registrations? If yes, did they use the same URL and/or the same metadata Hash?
1 registration and 1 re-registration with new metadata and hash via pooltool.

Thank you 🙏

Originally posted by @KtorZ in #2117 (comment)

**Comment by TurboEgon** [comment]
Are you using a 3rd party service / URL shortener to serve your metadata file?
First was gihub+shortener, second (when it disappeared) on pooltool (+extended metadata). Third on github without shortener

Did you make several registrations? If yes, did they use the same URL and/or the same metadata Hash?
See question 1. Everytime another url and hash

**Comment by glitch40** [comment]
> In order to help figuring out the problem, may any stake pool operator having issue here answer the two following questions:
> 
> #### Are you using a 3rd party service / URL shortener to serve your metadata file?
> #### Did you make several registrations? If yes, did they use the same URL and/or the same metadata Hash?
> Thank you 🙏

Hi KtorZ

There are issues you have quoted and some of these users may be experiencing them however the issue is between the cardano-wallet Api and the Daedalus wallet UI/UX  the wallet "stake pool" section stopped updating pools on the front in 3+ days ago as if it hit a hard limit around 430 - 450 pools even if you dump the chain and resync the wallet from zero there is no improvement or increase in pools. There are some tickers that use emoji's only in the ticker not sure if this is the issue or there is another issue. The pools will all show up from cardano-wallet api just not in Daedalus

**Comment by jeswanson86** [comment]
> In order to help figuring out the problem, may any stake pool operator having issue here answer the two following questions:
> 
> #### Are you using a 3rd party service / URL shortener to serve your metadata file?
> #### Did you make several registrations? If yes, did they use the same URL and/or the same metadata Hash?
> Thank you 🙏

1. Yes we used tinyurl.

2. Yes, attempted to register twice. The first we included a bad line in the metadata. The second was corrected. They were different hashes.

**Comment by KtorZ** [comment]
Thanks everyone. Fix is coming to `cardano-wallet`. There were two issues here:

a) Somehow a wrong URL posted on the chain which escaped an exception handler and ended up crashing the background worker responsible for fetching pool metadata.

b) Pools metadata were fetched with no particular priority, but by batches of 100. So if we ended with more than 100 pools with invalid metadata / unresponsive servers, those same 100 would be retried and retried until some would reach the maximum number of allowed retries and leave a seat for another pool metadata. Yet, since retrials can happen at least 72h after the first attempt, this could take a long time. The priority was changed to now favor new pools and those with small retry count first.

**Comment by cyber-russ** [comment]
> Thanks everyone. Fix is coming to `cardano-wallet`. There were two issues here:
> 
> a) Somehow a wrong URL posted on the chain which escaped an exception handler and ended up crashing the background worker responsible for fetching pool metadata.
> 
> b) Pools metadata were fetched with no particular priority, but by batches of 100. So if we ended with more than 100 pools with invalid metadata / unresponsive servers, those same 100 would be retried and retried until some would reach the maximum number of allowed retries and leave a seat for another pool metadata. Yet, since retrials can happen at least 72h after the first attempt, this could take a long time. The priority was changed to now favor new pools and those with small retry count first.

Good news- thanks for the fast response on this.

**Comment by VN121** [comment]
> Thanks everyone. Fix is coming to `cardano-wallet`. There were two issues here:
> 
> a) Somehow a wrong URL posted on the chain which escaped an exception handler and ended up crashing the background worker responsible for fetching pool metadata.
> 
> b) Pools metadata were fetched with no particular priority, but by batches of 100. So if we ended with more than 100 pools with invalid metadata / unresponsive servers, those same 100 would be retried and retried until some would reach the maximum number of allowed retries and leave a seat for another pool metadata. Yet, since retrials can happen at least 72h after the first attempt, this could take a long time. The priority was changed to now favor new pools and those with small retry count first.

Any time estimation on this?

**Comment by CrazyHolland** [comment]
Will this be fixed before end of epoch 0?


-------- Oorspronkelijk bericht --------
Van: Matthias Benkort <notifications@github.com>
Datum: 03-08-20 14:26 (GMT+01:00)
Aan: input-output-hk/daedalus <daedalus@noreply.github.com>
Cc: CrazyHolland <alexdegeus@hotmail.com>, Comment <comment@noreply.github.com>
Onderwerp: Re: [input-output-hk/daedalus] Pools are hidden in Daedalus randomly (#2117)


Thanks everyone. Fix is coming to cardano-wallet. There were two issues here:

a) Somehow a wrong URL posted on the chain which escaped an exception handler and ended up crashing the background worker responsible for fetching pool metadata.

b) Pools metadata were fetched with no particular priority, but by batches of 100. So if we ended with more than 100 pools with invalid metadata / unresponsive servers, those same 100 would be retried and retried until some would reach the maximum number of allowed retries and leave a seat for another pool metadata. Yet, since retrials can happen at least 72h after the first attempt, this could take a long time. The priority was changed to now favor new pools and those with small retry count first.

**Comment by KtorZ** [comment]
We are doing our best :)

**Comment by msuleman** [comment]
> > Thanks everyone. Fix is coming to `cardano-wallet`. There were two issues here:
> > a) Somehow a wrong URL posted on the chain which escaped an exception handler and ended up crashing the background worker responsible for fetching pool metadata.
> > b) Pools metadata were fetched with no particular priority, but by batches of 100. So if we ended with more than 100 pools with invalid metadata / unresponsive servers, those same 100 would be retried and retried until some would reach the maximum number of allowed retries and leave a seat for another pool metadata. Yet, since retrials can happen at least 72h after the first attempt, this could take a long time. The priority was changed to now favor new pools and those with small retry count first.
> 
> Any time estimation on this?



> Thanks everyone. Fix is coming to `cardano-wallet`. There were two issues here:
> 
> a) Somehow a wrong URL posted on the chain which escaped an exception handler and ended up crashing the background worker responsible for fetching pool metadata.
> 
> b) Pools metadata were fetched with no particular priority, but by batches of 100. So if we ended with more than 100 pools with invalid metadata / unresponsive servers, those same 100 would be retried and retried until some would reach the maximum number of allowed retries and leave a seat for another pool metadata. Yet, since retrials can happen at least 72h after the first attempt, this could take a long time. The priority was changed to now favor new pools and those with small retry count first.

Nice one, appreciate the transparency.

**Comment by msuleman** [comment]
> We are doing our best :)

Nice one, appreciate the transparency

**Comment by darrenjschumaker** [comment]
Matthias has been very helpful.  I'm sure they'll provide an ETA as soon as they are confident in one.

________________________________

**Comment by KtorZ** [comment]
I can't provide an ETA in the name of Daedalus. I can only provide one in the name of Adrestia (in charge of Daedalus' backend). 
Daedalus also has other fixes and changes they want to release.

**Comment by VN121** [comment]
> I can't provide an ETA in the name of Daedalus. I can only provide one in the name of Adrestia (in charge of Daedalus' backend).
> Daedalus also has other fixes and changes they want to release.

Sure we understand, but also look at it from people with an invisible stakepools view. We are being put in a severe disadvantage, that might never really correct itself. So please push this as hard as you guys can.

**Comment by darko-mijic** [comment]
> Any time estimation on this?

We are preparing Daedalus release which will go out today. @VN121

**Comment by darrenjschumaker** [comment]
Darko,
WIll Daedalus require the update be applied upon launching before proceeding?

________________________________

**Comment by VN121** [comment]
> > Any time estimation on this?
> 
> We are preparing Daedalus release which will go out today. @VN121

Please make it a mandatory update?

**Comment by darko-mijic** [comment]
>Please make it a mandatory update?

It will be.

**Comment by soulhacler** [comment]
I'm glad I found this. Thank you.

**Comment by darko-mijic** [comment]
![image](https://user-images.githubusercontent.com/4280521/89205174-97c19880-d5b7-11ea-8984-a10ae263563c.png)

**Comment by wtrask4** [comment]
Any chance to get this update out 2+ hours prior to epoch 209?

Would love to reassure my delegators that they are good for the first epoch of rewards.

**Comment by larestrepo** [comment]
My pool was in Daedalus, but just after making an update it just vanished from Daedalus. More than 700 pool registered and listed in pooltool.io. How many can you see in Daedalus? 

My delegators just have this thing:

![delegators](https://user-images.githubusercontent.com/48094194/89232676-8a9fac00-d5ad-11ea-81cd-c61943ba195a.PNG)

Very frustrating

**Comment by cardano-stake-and-relax** [comment]
Our stake pool RELAX has also disappeared from the list in Daedalus. We had to do a small update to our poolmeta.json file. Adjusted the json file, created new hash. Everything in pooltool and adapools looks correct. Just our delegators (and potential delegators) can't see us in the Daedalus program anymore. Unkown from epoch 210.

**Comment by VN121** [comment]
> Our stake pool RELAX has also disappeared from the list in Daedalus. We had to do a small update to our poolmeta.json file. Adjusted the json file, created new hash. Everything in pooltool and adapools looks correct. Just our delegators (and potential delegators) can't see us in the Daedalus program anymore. Unkown from epoch 210.

The worst thing is that 20% of all ADA are already staked. :(

**Comment by VN121** [comment]
> > Any time estimation on this?
> 
> We are preparing Daedalus release which will go out today. @VN121

@darko-mijic Got it!, thanks

**Comment by darrenjschumaker** [comment]
It’s out

--Darren
________________________________

**Comment by Griff1221** [comment]
https://iohk.zendesk.com/hc/en-us/articles/900002019226-Daedalus-2-0-1-Release-Notes

**Comment by cardano-stake-and-relax** [comment]
Thanks, pools were instantly visible again after installing new version and syncing 👍

**Comment by wtrask4** [comment]
Seems like there might still be a persistent issues.

My prior delegation appears as “Undelegated > SAGE”

But when I try to re-delegate it’s showing that I already have delegated...

I’m one of those with correct metapool then updated meta to include a new website then locked out of the last epoch.  
- that’s when the “undelegated > unknown” showed up

At least it seems I’m delegated but the UI display is strange.

![45819A0B-44EB-4EE4-8854-C34026708E14](https://user-images.githubusercontent.com/19297128/89240889-a9f10600-d5ba-11ea-897f-ada1b372a2d2.jpeg)

**Comment by cyber-russ** [comment]
Still no ADV after installing latest Daedalus. Showing in pooltools and adapools. ADVA pool (created while troubleshooting) showing correctly as retired. Should I attempt to re-register?

**Comment by tobg** [comment]
My Pool is visible now. thanks!

**Comment by poolmars** [comment]
> Seems like there might still be a persistent issues.
> 
> My 2.0.1 delegation appears as “Undelegated > SAGE”
> 
> But when I try to re-delegate it’s showing that I already have delegated...
> 
> I’m one of those with correct poolmeta then updated meta to include a new website then locked out of the last epoch.
> 
> * that’s when the “undelegated > unknown” showed up
> 
> At least it seems I’m delegated but the UI currently displayed is strange.

That's more a UX issue: it actually means "your current delegation" > "your future delegation". Since you're not delegated to anyone in the first 2 epochs, it shows "Undelegated".

**Comment by rjlust** [comment]
AGAPE does not show on Daedalus. My pool has not shown up since I first registered on the 31st. Just yesterday I modified my registration making sure to use modified metadata... but same URL. Is there anything else on my end I need to consider?

**Comment by A-Caccese** [comment]
Never experienced this bug before. Today I updated my metadata and now I'm not visible for the most part of the people searching for my pool: CSP. In my understanding, the fix for this in Daedalus 2.0.1 was not intended to be resolutive, but this bug it's a very big one. Most pool will lose the early delegators because of this.

**Are you using a 3rd party service / URL shortener to serve your metadata file?** 
No. I put my json file directly on the website server.
**Did you make several registrations? If yes, did they use the same URL and/or the same metadata Hash?**
Yes, I did at least 3 re-registrations in the last 24h. Same URL but different metadata hash.

**Comment by A-Caccese** [comment]
> 
> 
> Thanks everyone. Fix is coming to `cardano-wallet`. There were two issues here:
> 
> a) Somehow a wrong URL posted on the chain which escaped an exception handler and ended up crashing the background worker responsible for fetching pool metadata.
> 
> b) Pools metadata were fetched with no particular priority, but by batches of 100. So if we ended with more than 100 pools with invalid metadata / unresponsive servers, those same 100 would be retried and retried until some would reach the maximum number of allowed retries and leave a seat for another pool metadata. Yet, since retrials can happen at least 72h after the first attempt, this could take a long time. The priority was changed to now favor new pools and those with small retry count first.

Hi KtorZ, which value of the retry count is considered small? If I understand correctly, we have to wait 72h to be newly displayed (assuming no problem in the metadata hash), if we go over this?

**Comment by cyber-russ** [comment]
> AGAPE does not show on Daedalus. My pool has not shown up since I first registered on the 31st. Just yesterday I modified my registration making sure to use modified metadata... but same URL. Is there anything else on my end I need to consider?

AGAPE and ADA are 2 pools on the adapools Daedalus view that appear to both have registered fine based on the data presented (there are others), yet both are marked as having metadata or URL issues. In both cases I would note the pools have a significant pledge invested in ADA. Any advice please on how we can resolve? Is there actually an issue outstanding with registration (or the pools) or is there something that needs to happen on the IOHK side? Any help is gratefully received.

**Comment by KtorZ** [comment]
So I just did some investigation and indeed, it seems that both agapepool.ca and adavault.com use a version of TLS that our HTTP client does not support and the client / server are failing to handshake. I am currently checking whether it's using a version that is too old or something recent. I am suspecting the latter, since it seems that the Haskell http-client only added support for TLS-1.3 in a recent version (which we do not use at the moment :upside_down_face:).

**Comment by cyber-russ** [comment]
> So I just did some investigation and indeed, it seems that both agapepool.ca and adavault.com use a version of TLS that our HTTP client does not support and the client / server are failing to handshake. I am currently checking whether it's using a version that is too old or something recent. I am suspecting the latter, since it seems that the Haskell http-client only added support for TLS-1.3 in a recent version (which we do not use at the moment 🙃).

Yes pretty sure the ADAvault reverse proxy only supports TLS 1.3, I will add TLS 1.2,and test again....

Thanks for coming back quickly on this

**Comment by KtorZ** [comment]
Yeah, upgrading the library on our side also did the trick. Recent versions do support TLS-1.3, so every went just fine:

```
[cardano-wallet.pools-engine:Info:38] [2020-08-05 12:46:52.27 UTC] Fetching metadata with hash 2f970491 from https://adavault.com/adva.json
[cardano-wallet.pools-engine:Info:38] [2020-08-05 12:46:52.51 UTC] Successfully fetched metadata with hash 2f970491: StakePoolMetadata {ticker = StakePoolTicker {unStakePoolTicker = "ADVA"}, name = "ADAvault Alpha", description = Just "A secure and reliable pool with fair fees", homepage = "https://adavault.com"}
```

For agapepool however, the hash of the hosted metadata doesn't match the hash of the metadata published on chain:

```
[cardano-wallet.pools-engine:Info:39] [2020-08-05 12:47:51.16 UTC] Fetching metadata with hash e66d61a9 from https://agapepool.ca/agapepool.json
[cardano-wallet.pools-engine:Warning:39] [2020-08-05 12:47:51.74 UTC] Failed to fetch metadata with hash e66d61a9: Metadata hash mismatch. Saw: ed9ac60b250b95c25dc240e1d3b75e19c9128d95722ef5e2a8d20c5cbd100153, but expected: e66d61a95da755044893bbcb37a8b8613416c2133b4b5175bf9db62d352b4d94
```

Which makes me worry a bit about adapools not actually verifying hashes?

**Comment by cyber-russ** [comment]
Thanks for confirming,
I think adapools record Red as either bad hash OR bad URL based on Daedalus client which in case of ADV turns out to be accurate given the client would have been failing to fetch the URL using TLS1.2. They presumably scrape the rest of the data using a TLS1.3 complaint client.
What threw me was that I could get that hash using wget and the calculate using cardano-cli....but of course that wasn't an end to end test...

**Comment by rjlust** [comment]
https://agapepool.ca is TLS 1.3

**Comment by cyber-russ** [comment]
> Yeah, upgrading the library on our side also did the trick. Recent versions do support TLS-1.3, so every went just fine:
> 
> ```
> [cardano-wallet.pools-engine:Info:38] [2020-08-05 12:46:52.27 UTC] Fetching metadata with hash 2f970491 from https://adavault.com/adva.json
> [cardano-wallet.pools-engine:Info:38] [2020-08-05 12:46:52.51 UTC] Successfully fetched metadata with hash 2f970491: StakePoolMetadata {ticker = StakePoolTicker {unStakePoolTicker = "ADVA"}, name = "ADAvault Alpha", description = Just "A secure and reliable pool with fair fees", homepage = "https://adavault.com"}
> ```
> 
> For agapepool however, the hash of the hosted metadata doesn't match the hash of the metadata published on chain:
> 
> ```
> [cardano-wallet.pools-engine:Info:39] [2020-08-05 12:47:51.16 UTC] Fetching metadata with hash e66d61a9 from https://agapepool.ca/agapepool.json
> [cardano-wallet.pools-engine:Warning:39] [2020-08-05 12:47:51.74 UTC] Failed to fetch metadata with hash e66d61a9: Metadata hash mismatch. Saw: ed9ac60b250b95c25dc240e1d3b75e19c9128d95722ef5e2a8d20c5cbd100153, but expected: e66d61a95da755044893bbcb37a8b8613416c2133b4b5175bf9db62d352b4d94
> ```
> 
> Which makes me worry a bit about adapools not actually verifying hashes?

Apologies, but one last question as I would like to resolve this as quickly as possible. Should I push another registration by updating ADV metadata or just wait for it to feed through the system, I don't want to inadvertently trigger any additional delay.

**Comment by KtorZ** [comment]
We are updating the dependency in cardano-wallet, this will cascade down to Daedalus eventually. So, depends on how much you are willing to wait.

**Comment by rjlust** [comment]
I do verify the hash of the file by first hosting the file (modified for the re-registration I did) then I pull with wget and check the hash and build reg.cert, and complete the process. Have I done that the wrong way?

**Comment by KtorZ** [comment]
Doing so you _might_ have accidentally introduced a newline or some end of file character not present in the raw response from the server.

**Comment by cyber-russ** [comment]
> We are updating the dependency in cardano-wallet, this will cascade down to Daedalus eventually. So, depends on how much you are willing to wait.

Done- working. Thanks a lot for helping solve this.

**Comment by rjlust** [comment]
The first hash is the new registration poolmeta.json.
The expected Hash was the initial registration of the pool. I just
confirmed them on my end.

**Comment by jmcalle** [comment]
Hello,

We re-registered our stakepool (ADAVNZ) last night after some issues and changes affecting our hash metadata.

Ticker and metadata since then are pulled up correctly but still not showing in Daedalus 2.0.1

Metadata json is served through the same webserver.

I did make several registrations (first incorrect), later (yesterday) two more --> one to change metadata info and another to increase pledge.

**Comment by rjlust** [comment]
> Yeah, upgrading the library on our side also did the trick. Recent versions do support TLS-1.3, so every went just fine:
> 
> ```
> [cardano-wallet.pools-engine:Info:38] [2020-08-05 12:46:52.27 UTC] Fetching metadata with hash 2f970491 from https://adavault.com/adva.json
> [cardano-wallet.pools-engine:Info:38] [2020-08-05 12:46:52.51 UTC] Successfully fetched metadata with hash 2f970491: StakePoolMetadata {ticker = StakePoolTicker {unStakePoolTicker = "ADVA"}, name = "ADAvault Alpha", description = Just "A secure and reliable pool with fair fees", homepage = "https://adavault.com"}
> ```
> 
> For agapepool however, the hash of the hosted metadata doesn't match the hash of the metadata published on chain:
> 
> ```
> [cardano-wallet.pools-engine:Info:39] [2020-08-05 12:47:51.16 UTC] Fetching metadata with hash e66d61a9 from https://agapepool.ca/agapepool.json
> [cardano-wallet.pools-engine:Warning:39] [2020-08-05 12:47:51.74 UTC] Failed to fetch metadata with hash e66d61a9: Metadata hash mismatch. Saw: ed9ac60b250b95c25dc240e1d3b75e19c9128d95722ef5e2a8d20c5cbd100153, but expected: e66d61a95da755044893bbcb37a8b8613416c2133b4b5175bf9db62d352b4d94
> ```
> 
> Which makes me worry a bit about adapools not actually verifying hashes?

Since Daedalus is looking for the original registration metadata before I changed the pledge and updated the metadata. Should i be hosting the original metadata file so Daedalus can find it, or will it get resolved at some point? Should I be retiring the pool and starting again? Any help would be greatly appreciated. Thank you

**Comment by KtorZ** [comment]
@rjlust I believe it was just me here looking at the wrong logs. There were indeed 2 known registrations for this pool. We merged an update yesterday regarding TLS-1.3 support, Daedalus is aware and would include that in an upcoming release.

**Comment by hotlimbo** [comment]
I've just downloaded the latest version of Daedalus 2.1.0#14079.

It doesn't seem that Daedalus has resolved the issue where stakepools are missing in this second iteration of Daedalus 2.1.0.
My pools BRUN and BRUN0 don't appear anymore Daedalus.

**Comment by adapool** [comment]
Same Problem here after Daedalus 2.1.0 Update. My Pool doesn`t show up in Daedalus. On the adapools.org Website it is marked red (bad meta-hash or fetching meta.json). I have now deregistered the Pool, set up a new one and hosting the new poolmetadata.json on a different site. The new Pool appeared on Daedalus immediately.

**Comment by TurboEgon** [comment]
> I've just downloaded the latest version of Daedalus 2.1.0#14079.
> 
> It doesn't seem that Daedalus has resolved the issue where stakepools are missing in this second iteration of Daedalus 2.1.0.
> My pools BRUN and BRUN0 don't appear anymore Daedalus.

The initial issue (one third of pools were not shown) is already solved. Maybe your pools are not shown in daedalus, because your both relays are offline? I dont know if daedalus checks this but I can imagine

**Comment by hotlimbo** [comment]
> 
> 
> > I've just downloaded the latest version of Daedalus 2.1.0#14079.
> > It doesn't seem that Daedalus has resolved the issue where stakepools are missing in this second iteration of Daedalus 2.1.0.
> > My pools BRUN and BRUN0 don't appear anymore Daedalus.
> 
> The initial issue (one third of pools were not shown) is already solved. Maybe your pools are not shown in daedalus, because your both relays are offline? I dont know if daedalus checks this but I can imagine



Thanks for replying. The issue has resolved. Here is what was the problem:

My old current pool cert and future pool cert were both pointing to the same metadata file. That metadata file was updated to reflect the new updated metadata for my future pool cert. To mitigate that problem what I did was to restore the old pool metadata file, left it where it was before. Then I created the new metadata file for the future pool cert, gave it another name and had that sit on my web site alongside the older metadata file.

So the issue was a hash mismatch initally.  Then, since the hash probably fell out of daedalus because of some cacheing issue there, that was to show people my old pool params, and not the future ones, I had to wait till Daedalus retried.

In the end it returned to the Daedalus wall of pools.

**Comment by snajjar** [comment]
Same issue yesterday for SPFR. Was displayed on several machine's Daedalus, but not on a freshly installed Daedalus (100% synchronized).

**Comment by sp33dy** [comment]
Good afternoon. Can you help? We have registered Buzz and can't see it in Daedalus now, yet it is in every other tool (pooltool, adapools & pm.tool). However, strangely it did this morning. Let me explain the situation:

Yesterday, a pool registered with BUZZ. The Cardano Buzz owner (from ITN) was alerted and asked them to move over (which they kindly did to IBee) and I was asked to create the pool. I did that early evening yesterday, but couldn't see Buzz, when I realised I needed to uppercase BUZZ; after which all was good and it was appearing last night and this morning.

This morning, Cardano Buzz contacted me with the witness details for from the ITN and I reregistered with the new details. This all worked and the nice green tick appeared in Daedalus. Cardano Buzz redelegated his funds and he fired off the marketing to inform people. All happy.

Just a few hours later, BUZZ disappeared (he was contacted by someone wanting to redelegate over). I've poked the re-registration several times and can see pooltool/adapools change. Suspecting it might be the metadata hash from Pooltool, I then published using a github file instead; for which I've removed the ITN tick, so it's here right now:

https://git.io/JtC5R

Quite simply, have we been locked out for trying to get this work by over re-registering? We urgently need to get this showing and would appreciate advise as to what we should do??

Kind regards

**Comment by KtorZ** [comment]
@sp33dy Daedalus (unlike other tools like pooltool, adapools or pm.tool) does actually verify that the JSON metadata file served at the URL indicated does match the hash also registered on-chain. This is to prevent malicious stake pool operators from serving potentially malicious content to users. 

In most cases where people have reported their pool not showing up in Daedalus, it's been because the hash specified on-chain wasn't matching the hash re-computed from the hosted metadata. Often it's because of extra newlines or end of file characters added when serving the file. So please, double-check that the binary octet-stream representing your metadata does indeed match exactly what you've specified on-chain in the latest pool registration certificate.

**Comment by sp33dy** [comment]
Hi KtorZ, I would agree if I didn't have this scripted and checked; it's why I've tried multiple times with the reregistering.

The existing metadata lives here: https://git.io/JtC5R

{
"name": "Cardano Buzz",
"description": "The official OG Cardano Buzz pool",
"ticker": "BUZZ",
"homepage": "https://www.cardano.buzz"
} 

that computes to: 041e08026e81b7c973a67a276f611b162b8743b31fdde20749b3c56dd0bedc3d

That is confirmed in pool tool (as the current metadata submitted)

Metadata last checked: January 27th 2021, 3:29:19 pm
URL: https://git.io/JtC5R
Hash: 041e08026e81b7c973a67a276f611b162b8743b31fdde20749b3c56dd0bedc3d
metadata pool description: The official OG Cardano Buzz pool
metadata pool homepage: https://www.cardano.buzz
metadata pool name: Cardano Buzz

So I'm rerunning the registration now with:

    --metadata-url "https://git.io/JtC5R" \
    --metadata-hash "041e08026e81b7c973a67a276f611b162b8743b31fdde20749b3c56dd0bedc3d" \

which match up. Clicking now and will check.

**Comment by sp33dy** [comment]
F* that solves it! That Hash is coming out all wrong.

**Comment by gitmachtl** [comment]
Have you checked if the smash server has picked you up already? There were issues with the smash server lately.

**Comment by sp33dy** [comment]
Hi @gitmachtl , no is the honest answer. How can I do that?

**Comment by gitmachtl** [comment]
You can call the Smash-Server like:

**Comment by gitmachtl** [comment]
You can call the Smash-Server like:
`https://smash.cardano-mainnet.iohk.io/api/v1/metadata/<poolid>/<metahash>`

Replace the <poolid> with your Pool-ID in hex or bech format and <metahash> with your Meta-Hash in hex.

So in your case its: https://smash.cardano-mainnet.iohk.io/api/v1/metadata/52122387c3e805e5d97bda13a85a384ba63110bbf6045df79b29f922/041e08026e81b7c973a67a276f611b162b8743b31fdde20749b3c56dd0bedc3d

This shows me, that the SmashServer has not picked you up at the time of checking here.

**Comment by nikolaglumac** [comment]
Your stake pool **won't show up** in Daedalus in case it is not picked up by IOHK SMASH server first.

**Comment by lukas-kamleitner** [comment]
I currently have the same issue. 
When will SMASH pick up updated pools? Is there a way to force an update?

**Comment by nikolaglumac** [comment]
It should be almost instant.

@gitmachtl @sp33dy BUZZ stake pool is now visible on SMASH: https://smash.cardano-mainnet.iohk.io/api/v1/metadata/52122387c3e805e5d97bda13a85a384ba63110bbf6045df79b29f922/041e08026e81b7c973a67a276f611b162b8743b31fdde20749b3c56dd0bedc3d

**Comment by disassembler** [comment]
Smash was stuck, I smashed it and it's processing new requests again.

**Comment by lukas-kamleitner** [comment]
Thanks! 

Mine is now also visible on SMASH (but it took 3 hours).
Still not visible in Daedalus

**Comment by disassembler** [comment]
We're working to get some better operating metrics provided by the service. The wallet has an exponential retry back-off, so restarting daedalus should show it, or just wait until it's retry timer kicks.

**Comment by sp33dy** [comment]
I figured out what I think has occured, which leads me to ask, has SMASH been processing today:

(1) Last night I registered Buzz correctly and Daedalus was showing
(2) This morning, we delegated into it; all good
(3) The ITN Witness details were provided, so I re-registered. At that point, we took a snapshot (I thought of Daedalus, it wasn't, it was in Pooltool which shows ok). Looking at the request to SMASH server, it doesn't have our entry, even though it is well formed and has the correct hash.
(4) During the day, I've tried 4 or 5 re-registrations and NONE appear in the SMASH server

This leads me to point a very pointy finger at the Smash server. I thought we saw the ITN Green tick in Daedalus; but that's not true...

Help? How do we find out if SMASH is running.

P.S. Yoroi is all ok.

**Comment by sp33dy** [comment]
> 
> 
> It should be almost instant.
> 
> @gitmachtl @sp33dy BUZZ stake pool is now visible on SMASH: https://smash.cardano-mainnet.iohk.io/api/v1/metadata/52122387c3e805e5d97bda13a85a384ba63110bbf6045df79b29f922/041e08026e81b7c973a67a276f611b162b8743b31fdde20749b3c56dd0bedc3d

Thanks, but no sign in Daedalus; restarted...

**Comment by lukas-kamleitner** [comment]
Mine neither

**Comment by lukas-kamleitner** [comment]
@sp33dy how did you get your pool to show up on Daedalus? Did you do something else?

**Comment by nikolaglumac** [comment]
@sp33dy @lukas-kamleitner if it is visible on SMASH it will be also visible in Daedalus - you just have to wait for it.
I can see BUZZ in Daedalus. Not sure what's that ticker of your stake pool @lukas-kamleitner but I am sure it is in Daedalus too.

**Comment by sp33dy** [comment]
Good morning. The smash server didn't do us any favour. This morning, I have reports that BUZZ can be seen by others, but not for me. Given that, I've taken the drastic step of deleting the chain and cache folders in the appdata directory. I'm now waiting for a full synch. I expect that to fix my issue. In flight, it shows!

**Comment by nikolaglumac** [comment]
@sp33dy it will show up eventually. I am sure of that.

**Comment by lukas-kamleitner** [comment]
Yes, I can see mine now. My ticker is [ALPS]. But I lost ~10 delegators yesterday and got 7 emails that my pool is displayed as unknown. 

How can we prevent such an error in the future?

**Comment by nikolaglumac** [comment]
Re-registering stake pool leads to this behavior. I am not sure this can be avoided...

**Comment by lukas-kamleitner** [comment]
Yeah, but how can we check if SMASH is running?

**Comment by lukas-kamleitner** [comment]
I would have waited with the update process if I had known, that SMASH was lagging

**Comment by nikolaglumac** [comment]
I can not give you that answer. Please post your question on https://github.com/input-output-hk/smash

**Comment by lukas-kamleitner** [comment]
Thanks, will do
