### ISSUE TITLE
Cannot start 4.5.0 - DbLocked

### ISSUE THREAD

**Issue by CherryDT** [input-output-hk/daedalus#2746]
**EDIT: Here is the workaround for people finding this on Google:**

> As a workaround, you can do the following (every time you start Daedalus):
> 
> Open the file `%appdata%\Daedalus Mainnet\config.json` in an editor. (Maybe create a backup first.) Find the line that contains `mainnet-PREVIOUS-CARDANO-PID` and delete it. If this was the last line in the file before the final `}`, delete the comma at the end of the previous line as well. Then start Daedalus and it will work one time.

---

I got an update from 4.4.1 to 4.5.0 today.

After the update, I can no longer start Daedalus. It goes in a cycle of "Connecting to network", "Stopping cardano node", "Cardano node crashed".

`node.log` shows that it keeps crashing with the `DbLocked` error:

```
DbLocked "C:\\Users\\david\\AppData\\Roaming\\Daedalus Mainnet\\chain\\lock"

cardano-node: The db is used by another process. File "C:\Users\david\AppData\Roaming\Daedalus Mainnet\chain\lock" is locked
```

At this point, there are always two instances of `cardano-node.exe` running - one using 4 GB of RAM, and one that runs, crashed, gets restarted, etc.

I already tried several times to close Daedalus, make sure no cardano-node.exe process runs, deleted the lockfile is existing, etc. - but again, when I start Daedalus, it starts again *two* instances, with the second one obviously failing.

![image](https://user-images.githubusercontent.com/6010463/142448843-9e51c29c-a767-4ceb-a1ba-181648b4694a.png)

What can I do to fix this?

**Comment by CherryDT** [comment]
I tried attaching a debugger to understand what's going on.

Apparently Daedalus is checking the wrong PID somehow. It checks PID 34200 all the time (this process doesn't exist). Also, there is an error about failing to store the PID (empty in this case, because it _did_ detect that 34200 is no longer running).

![image](https://user-images.githubusercontent.com/6010463/142454437-e1c5c2e6-c069-4b19-a59d-ee0f63d6b036.png)

This is because it calls `store.set("mainnet-PREVIOUS-CARDANO-PID", undefined)` instead of `store.delete("mainnet-PREVIOUS-CARDANO-PID")`.

I finally solved the problem by manually deleting the line `	"mainnet-PREVIOUS-CARDANO-PID": 28844,` from `config.json`. Still this is a bug that can leave Daedalus in an unusable state, and normal users can't be expected to figure out this solution.

**Comment by dmitrii-gaico** [comment]
@CherryDT Hello. Thank you for your research and such a detailed report.
We are currently investigating the issue in order to fix it asap.

Please let me know if it works now as expected after your tweak.

Thank you in advance.

**Comment by CherryDT** [comment]
Hm, no, seems it works only _once_ this way. After closing Daedalus, the `mainnet-PREVIOUS-CARDANO-PID` again doesn't get removed and next time it will go into the same cycle as described above. I have to manually delete this line every time I want to start Daedalus.

**Comment by dmitrii-gaico** [comment]
@CherryDT Can you please provide the Logs zipped?
Thank you!

**Comment by CherryDT** [comment]
Sent you an email.

**Comment by dmitrii-gaico** [comment]
Can you please attach the Log.zip to this card in GH ?
Thank you in advice!

**Comment by CherryDT** [comment]
Just to confirm, it won't contain any sort of sensitive information?

**Comment by dmitrii-gaico** [comment]
@CherryDT Yes, it doesn't not contain any sensitive information. However I have received the logs so thank you! No need to attach it.
Thank you , we are continue the research.

**Comment by CherryDT** [comment]
On that note, I looked at the log files now because I'd have removed anything problematic and then posted here, but I discovered that there _is_ problematic information in `wallet-migration-report.json`. It showed names of wallets.

**Comment by CherryDT** [comment]
This is my `config.json` by the way, in case it's relevant:

![image](https://user-images.githubusercontent.com/6010463/142596225-69b6696f-ab05-4e9c-b195-08d91a422554.png)

**Comment by dmitrii-gaico** [comment]
@CherryDT by now to have your Daedalus back in a good shape I suggest you to perform a clean re-installation process.
Unfortunately you would need to Sync the chain from the scratch. Please make sure you have all your mnemonics near by so you can restore your wallets once Node is fully synced.
Please follow the instruction https://iohk.zendesk.com/hc/en-us/articles/360013170694-Uninstall-Daedalus-and-remove-wallet-s-data
Thank you!

**Comment by CherryDT** [comment]
This is _very_ inconvenient. How come that something that looks like an issue in controlling the state of the cardano node (from the outside) would require the chain to be resynced? Can't I keep the "chain" folder and put it back after reinstallation?

**Comment by dmitrii-gaico** [comment]
Yes, you can try to keep the chain folder and use it after the re-installation but I cant guarantee that it would resolve the crashing loop issue. You can try this is as a Plan A and if it doesn't helps then Re-install + full re-sync is a Plan B.

**Comment by CherryDT** [comment]
I don't think this will help, thanks anyway for the suggestion. Instead I investigated the root cause and fixed it. See https://github.com/input-output-hk/daedalus/pull/2749

**Comment by greg-pendlebury** [comment]
Thanks for the analysis and workaround. Daedalus has been broken for me all day until I found this workaround. Hope the fix is pushed through so I don't have to keep cleaning up the config file. I can confirm I was seeing the same symptoms of two nodes starting on my PC and contending for the lock file. One was healthy and processing the chain data, whilst the other was perma-crash looping. It wasn't clear to me whether the healthy node was a singular instance online the whole time, or just one node that gets to do work before restarting. The wallet was complaining the whole time.

**Comment by danielmain** [comment]
> Thanks for the analysis and workaround. Daedalus has been broken for me all day until I found this workaround. Hope the fix is pushed through so I don't have to keep cleaning up the config file. I can confirm I was seeing the same symptoms of two nodes starting on my PC and contending for the lock file. One was healthy and processing the chain data, whilst the other was perma-crash looping. It wasn't clear to me whether the healthy node was a singular instance online the whole time, or just one node that gets to do work before restarting. The wallet was complaining the whole time.

Thank you @greg-pendlebury for your feedback!
Would you pls tell me what is your operating system?

**Comment by danielmain** [comment]
Hi @CherryDT thank you so much for the PR. 

It is a long story, originally another problem related to how do we start cardano-node implemented [here](https://github.com/input-output-hk/daedalus/pull/2735#issue-1047468519) caused this race condition. Your code definitely solves one side of the puzzle, that is why we will provide a complete fix very soon!

Thank you for your time and your suggestions!

**Comment by greg-pendlebury** [comment]
> > Thanks for the analysis and workaround. Daedalus has been broken for me all day until I found this workaround. Hope the fix is pushed through so I don't have to keep cleaning up the config file. I can confirm I was seeing the same symptoms of two nodes starting on my PC and contending for the lock file. One was healthy and processing the chain data, whilst the other was perma-crash looping. It wasn't clear to me whether the healthy node was a singular instance online the whole time, or just one node that gets to do work before restarting. The wallet was complaining the whole time.
> 
> Thank you @greg-pendlebury for your feedback! Would you pls tell me what is your operating system?

Windows 10

**Comment by nikolaglumac** [comment]
Hi!
This issue should be fixed in the latest release 4.5.1.
Can you please see if it works?
Thanks!

**Comment by CherryDT** [comment]
Hi, thank you, but I think the bug is still lingering. From how I understand, the commit https://github.com/input-output-hk/daedalus/pull/2755/commits/44fcccbebfe56087effa5f934e468eb3fcaf9c9d does remove the trigger that made it appear most of the time by removing on of the disk space check calls, and the window for the race condition is now probably smaller (actually I originally somehow assumed that `_canBeStarted` would already check for `STARTING` - but apparently it didn't, and adding that solves a lot already), but the race condition as I described it still exists.

Imagine:

* status is `STOPPED`
* invocation A of `start` happens
* invocation B of `start` happens
* in invocation A, `start` calls `_canBeStarted`
* in invocation A, `_canBeStarted` passes the first condition since state is currently still `STOPPED`
* in invocation A, `_canBeStarted` asynchronously calls `_ensurePreviousCardanoNodeIsNotRunning`
* in invocation B, `start` calls `_canBeStarted` (possible because it's asynchronous)
* in invocation B, `_canBeStarted` **also** passes the first condition and now calls `_ensurePreviousCardanoNodeIsNotRunning`
* in invocation A, `_canBeStarted` returns `true`, and `start` sets status to `STARTING`, but it's already too late
* in invocation B, `_canBeStarted` **also** returns `true`

The only way to prevent this would be to have another state that is set synchronously before `_canBeStarted` is called, which is why I introduced a separate flag in my PR for this (piggy-backing on the node state is not possible here).

Please review it again, to get rid of this race condition entirely! Thanks

**Comment by nikolaglumac** [comment]
Thanks @CherryDT!
We are refactoring that part at the moment. 
Thank you for the pointers - we will make sure all race conditions are eliminated.

**Comment by dmitrii-gaico** [comment]
Closing the ticket as the team is working on improvements and most of the discussed issues supposed to resolved in 4.5.2 release.
Please create a new ticket if you still experience any issues described.
Thank you!
