### ISSUE TITLE
Restoring wallet keeps spining

### ISSUE THREAD

**Issue by rnkhouse** [input-output-hk/daedalus#571]
I am trying to restore my wallet and its not working.

Logs:
[2017-12-01 17:11:07:0216] [debug] Local difficulty changed: 298116
[2017-12-01 17:11:07:0216] [debug] Network difficulty changed: 298116
[2017-12-01 17:11:07:0610] [debug] Local difficulty changed: 298116
[2017-12-01 17:11:07:0610] [debug] Network difficulty changed: 298116
[2017-12-01 17:11:09:0171] [debug] CardanoClientApi::getWallets called
[2017-12-01 17:11:09:0173] [debug] CardanoClientApi::syncProgress called
[2017-12-01 17:11:09:0197] [debug] CardanoClientApi::nextUpdate called
[2017-12-01 17:11:09:0258] [debug] CardanoClientApi::getWallets success: []
[2017-12-01 17:11:09:0259] [debug] CardanoClientApi::nextUpdate success: No updates available
[2017-12-01 17:11:09:0262] [debug] CardanoClientApi::syncProgress success: {
  "_spLocalCD": {
    "getChainDifficulty": {
      "getBlockCount": 298116
    }
  },
  "_spNetworkCD": {
    "getChainDifficulty": {
      "getBlockCount": 298116
    }
  },
  "_spPeers": 0
}

When I quit the app and start it again I am getting connecting to network message but it's not connecting.....

Please advice.

**Comment by gitmalong** [comment]
Same problem :( (Mac OS High Sierra).

**Comment by cleverca22** [comment]
it may take up to an hour to restore, and there is a possible bug that stops it from connecting until the restore has finished

**Comment by stepanhack** [comment]
Yup, restores fine for me too, but it took a lot of time

**Comment by ksallberg** [comment]
I am seeing this issue on OSX sierra, using Daedalus 1.0.3619. 

I will have not waited for an hour yet, but will do that.

I saved "Wallet-1.0" and "Secrets-1.0" and copying these back to ~/Library/Application Support/Daedalus makes Daedalus start quickly and normally.

**Comment by ksallberg** [comment]
I can confirm that the "wallet" eventually restores. I suggest to place a friendly, informative text on the restore page, stating that it might take some time. I initially expected this to be fast and so thought it might be a bug.

**Comment by Jeffro1979** [comment]
I am having the same issue.  I've reproduced it on multiple computers.  It just sits there spinning.  The longest I have waited is about 4 hours.  Should I wait longer?  I also don't feel comfortable walking away from my computer with my recovery seed sitting right there on the screen for hours.  Can we expect a better wallet from this organization soon?

**Comment by Jeffro1979** [comment]
So this is to say that the ADA token has ZERO liquidity right now everyone experiencing this?  This is one of the most horrible things to happen to a user/investor.

**Comment by ksallberg** [comment]
@Jeffro1979 do you experience this when installing the wallet for the first time, or complete re-install? It happened to me only when I tampered with the stored files and restarted. I kept it going over night to make it complete

**Comment by tanzeelrana** [comment]
Horrible design implemented on restore wallet. Who ever designed this was not thinking of external developers being easily able to use this function

**Comment by tanzeelrana** [comment]
To resolve this issue you guys need to change the request response architecture. I can help redesign. Currently I have to write my own backend to support this behaviour. Its strange that the engineers are not following the correct design practices in a team such as cardano. I have really high hopes for this project man !

**Comment by Jeffro1979** [comment]
This must be a part of the "technical debt" the team is hoping to resolve
soon.

**Comment by c0ndensate** [comment]
Check out this issue and see very last post. Try turning off real-time protection
https://github.com/input-output-hk/daedalus/issues/618

**Comment by sublimator** [comment]
One hour?? This is ridiculously bad ...

**Comment by tkulis** [comment]
I can also confirm that Wallet restored after a maybe 50 minutes  , but after I close it and reopened it, I get this annoying message "Connecting to network..." and I waited like 2, 3 hours and nothing happens. It is very frustrating thing(guys give us some more informative msgs at least). Someone mentioned somewhere that this can be due to a large number of files which are used by Wallet on Windows machines, I can say that this is good direction, because it is well known that windows is very bad performer when it comes to(create/delete/update/move) large number of small files. By the way mashine is running on **Windows 10 Pro**, details bellow 
![image](https://user-images.githubusercontent.com/8543254/36140106-5c737976-10a0-11e8-96f4-0169a38a2e9c.png)

**Comment by sublimator** [comment]
Even syncing the chain is pretty slow really. The experience doesn't match
the expectations set by the supposed caliber of the team. Hopefully it will
all be fixed in due time.

**Comment by tkulis** [comment]
So guys after more than 4 hours I still have this loading screen "Connecting to network..." :( :( .
"cardano-node - Copy.LOG" => I shorted this LOG , because it file was 300MB big, and couldn't attached it here

[Daedalus - Copy.LOG](https://github.com/input-output-hk/daedalus/files/1719958/Daedalus.-.Copy.LOG)
[cardano-node - Copy.LOG](https://github.com/input-output-hk/daedalus/files/1719969/cardano-node.-.Copy.LOG)

**Comment by sublimator** [comment]
Awwww :/

**Comment by i06** [comment]
Hey, Please see that article. May it will help you
[tutorial-to-restore-your-cardano-from-daedalus-wallet-successfully-with-the-wallet-has-many-bugs](https://steemit.com/ada/@angular/tutorial-to-restore-your-cardano-from-daedalus-wallet-successfully-with-the-wallet-has-many-bugs)

**Comment by ksallberg** [comment]
I'm not a dev on this but last time I restored my wallet, I just left the process on during the night. So depends on if you can manage what you propose faster than during the night. And if the improvement will be enough to "win" against over night.

**Comment by chisNaN** [comment]
THanks again

**Comment by un1t** [comment]
Finally it worked out.
It took 8 hours to restore a wallet on already synced node! It's unbelievably slow.
So from scratch it takes 2 days, one day for syncing and other day for restoring.
Ok, I could understand why we need a day to sync. But restoring should take a few seconds, or few minutes at most (if we do not have any indices at all).

**Comment by sublimator** [comment]
wow, even with the latest wallet build ??

they just made it "async" rather than the scary stalled thingy ??

**Comment by un1t** [comment]
@sublimator 
> wow, even with the latest wallet build ??
DAEDALUS 0.9.1 Windows build 1.1.5813, with Cardano 1.1.1

> they just made it "async" rather than the scary stalled thingy ??
I don't know how it worked before now. Seems you can create new wallet or try to restore more wallets during this process. So it's not completely stuck.

**Comment by nikolaglumac** [comment]
Restoration times have been greatly reduced in the latest Daedalus releases.
Still, depending on your machine specs and other software you are running, the restoration process could potentially take quite a while: https://iohk.zendesk.com/hc/en-us/articles/360010559413-Restoring-wallet-takes-2-weeks
